### ISSUE TITLE
[!] An error occurred while processing the pre-install hook of the Podfile.

### ISSUE THREAD

**Issue by b08Walls** [homeeondemand/react-native-mapbox-navigation#44] opened 2021-07-16 15:34 UTC
Hello and good day, 

Working with my development team we ran into this issue when installing pods with the latest version of your package:

`[!] An error occurred while processing the pre-install hook of the Podfile.

undefined method `pre_install' for nil:NilClass

/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:162:in `pre_install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:869:in `run_podfile_pre_install_hook'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:857:in `block in run_podfile_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:856:in `run_podfile_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:254:in `block in download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:252:in `download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'`

As a temporary fix for anyone running into this issue we just rolled back to version 1.0.7, but it would be nice to know the right way to work with the latest version if there is any. 

Thank you.

**Comment by rossmartin** [comment] 2021-07-16 16:03
Hey thank you for reporting this. This is fixed with the latest version, `1.0.9`.

**Closed by rossmartin** 2021-07-16 16:03 UTC

**Comment by JorgeQuevedoC** [comment] 2021-07-17 16:08
Hi @rossmartin, I am on the team with @b08Walls and after you released version 1.0.9 I tried to update the package and this time I get the error attached
![Screen Shot 2021-07-17 at 10 52 17 AM](https://user-images.githubusercontent.com/19591200/126042728-101e687b-4cb8-47c8-908c-68dcbcd04b52.png)

**Comment by rossmartin** [comment] 2021-07-17 16:30
> Hi @rossmartin, I am on the team with @b08Walls and after you released version 1.0.9 I tried to update the package and this time I get the error attached

Hmm that's strange. I can't reproduce.

Can you please try deleting your `ios/Podfile.lock` file and your `ios/Pods` folder? Then do a `pod install` and see if it will build.

**Comment by vitaliykreminskiy** [comment] 2022-01-27 14:08
Had the same issue. Removing the react-native-mapbox-navigation from the project and adding it back again solved the issue for me. Maybe that was linking issue
